# Generated by Django 3.1.6 on 2021-02-14 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completedAt',
            field=models.DateTimeField(blank=True),
        ),
    ]
