# Generated by Django 3.1.6 on 2021-02-14 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0005_auto_20210214_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completedAt',
            field=models.DateTimeField(null=True),
        ),
    ]
